# Generated by Django 4.2.9 on 2024-08-16 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.CharField(max_length=255)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('cantidad', models.IntegerField()),
                ('destino', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=50)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('solicitado', models.CharField(max_length=255)),
            ],
        ),
    ]
