# Generated by Django 4.2.9 on 2024-08-16 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_solicitud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
    ]
