# Generated by Django 4.2.9 on 2024-08-16 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_orden'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anticipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=100)),
                ('cantidad', models.PositiveIntegerField()),
                ('centro_costo', models.CharField(max_length=50)),
                ('producto_servicio', models.CharField(max_length=100)),
                ('vlr_unitario', models.DecimalField(decimal_places=3, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=3, max_digits=10)),
                ('iva', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('retencion', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('total_pagar', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('aprobado', models.BooleanField(default=False)),
            ],
        ),
    ]
