# Generated by Django 4.2.9 on 2024-08-28 01:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_diario_anticipo_fecha_solicitud_estado_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.AlterField(
            model_name='anticipo',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='anticipo',
            name='subtotal',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='diario',
            name='tiempo_entrega',
            field=models.TimeField(verbose_name='Hora de Entrega'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
