# Generated by Django 4.2.9 on 2024-09-23 02:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_orden_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='oculto',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor', models.CharField(max_length=255)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('detalles', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada')], default='pendiente', max_length=50)),
                ('cotizacion_pdf', models.FileField(blank=True, null=True, upload_to='cotizaciones_pdfs/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('estado_aprobada', models.BooleanField(default=False)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones', to='home.solicitud')),
            ],
        ),
    ]
