# Generated by Django 4.2.9 on 2024-09-24 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_solicitud_oculto_cotizacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anticipo',
            name='aprobado',
        ),
        migrations.AlterField(
            model_name='anticipo',
            name='fecha',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='anticipo',
            name='iva',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='anticipo',
            name='retencion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='anticipo',
            name='subtotal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='anticipo',
            name='total_pagar',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='anticipo',
            name='vlr_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='cotizacion_pdf',
            field=models.FileField(blank=True, null=True, upload_to='cotizaciones_pdfs/'),
        ),
        migrations.AlterField(
            model_name='diario',
            name='medio_pago',
            field=models.CharField(choices=[('cuentas_por_pagar', 'Cuentas por Pagar'), ('caja_compra', 'Caja de Compra'), ('tarjeta_debito', 'Tarjeta Débito'), ('caja_paula', 'Caja de Paula')], max_length=200),
        ),
        migrations.AlterField(
            model_name='diario',
            name='tiempo_entrega',
            field=models.DateTimeField(verbose_name='Hora de Entrega'),
        ),
    ]
