# Generated by Django 4.2.9 on 2024-09-26 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_anticipo_valor_iva_anticipo_valor_retencion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anticipo',
            name='aprobado',
            field=models.BooleanField(default=False),
        ),
    ]
