# Generated by Django 4.2.9 on 2024-09-26 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_anticipo_aprobado'),
    ]

    operations = [
        migrations.AddField(
            model_name='anticipo',
            name='oculto',
            field=models.BooleanField(default=False),
        ),
    ]
