# Generated by Django 4.2.9 on 2024-10-07 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0016_alter_diario_tiempo_entrega_mensaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='diario',
            name='oculto',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='usuario',
            field=models.ForeignKey(default=50, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=50),
        ),
    ]
