# Generated by Django 4.2.9 on 2024-10-07 19:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0017_diario_oculto_solicitud_usuario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='solicitado',
        ),
        migrations.AddField(
            model_name='diario',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to=settings.AUTH_USER_MODEL),
        ),
    ]
