# Generated by Django 4.2.9 on 2024-10-19 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_remove_cotizacion_cotizacion_pdf_cotizacion_archivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diario',
            name='destino',
            field=models.CharField(choices=[('ADMINISTRACIÓN', 'ADMINISTRACIÓN'), ('PRODUCCION', 'PRODUCCION'), ('ALEVINERA', 'ALEVINERA'), ('ECOPEZ', 'ECOPEZ'), ('FERRY', 'FERRY'), ('CARRO PESCA NVS 228', 'CARRO PESCA NVS 228'), ('CARRO PESCA WGY 964', 'CARRO PESCA WGY 964'), ('CARRO PESCA THS 473', 'CARRO PESCA THS 473'), ('CARRO PESCA SRP 254', 'CARRO PESCA SRP 254'), ('CARRO EXPORTACION GQZ 727', 'CARRO EXPORTACION GQZ 727'), ('CARRO EXPORTACION GRK 030', 'CARRO EXPORTACION GRK 030'), ('CARRO EXPORTACION THS 592', 'CARRO EXPORTACION THS 592'), ('UNIDAD COMERCIALIZACION', 'UNIDAD COMERCIALIZACION')], max_length=200),
        ),
    ]
