# Generated by Django 4.2.9 on 2024-10-21 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_remove_diario_documento_pdf_diario_documento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orden',
            name='estado',
        ),
    ]
