# Generated by Django 4.2.9 on 2024-10-30 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_remove_orden_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
