# Generated by Django 4.2.9 on 2024-12-06 16:02

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_alter_orden_precio'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteCombustible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('combustible', models.CharField(choices=[('GASOLINA', 'Gasolina'), ('ACPM', 'ACPM')], max_length=10)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('codigo_estacion', models.CharField(max_length=50)),
                ('empresa', models.CharField(max_length=100)),
                ('centro_costo', models.CharField(choices=[('ADMINISTRACIÓN', 'ADMINISTRACIÓN'), ('PRODUCCION', 'PRODUCCIÓN'), ('ALEVINERA', 'ALEVINERA'), ('ECOPEZ', 'ECOPEZ'), ('FERRY', 'FERRY'), ('CARRO PESCA NVS 228', 'CARRO PESCA NVS 228'), ('CARRO PESCA WGY 964', 'CARRO PESCA WGY 964'), ('CARRO PESCA THS 473', 'CARRO PESCA THS 473'), ('CARRO PESCA SRP 254', 'CARRO PESCA SRP 254'), ('CARRO EXPORTACION GQZ 727', 'CARRO EXPORTACIÓN GQZ 727'), ('CARRO EXPORTACION GRK 030', 'CARRO EXPORTACIÓN GRK 030'), ('CARRO EXPORTACION THS 592', 'CARRO EXPORTACIÓN THS 592'), ('UNIDAD COMERCIALIZACION', 'UNIDAD COMERCIALIZACIÓN')], max_length=50)),
                ('destino', models.CharField(choices=[('PRODUCCION', 'PRODUCCIÓN'), ('ECOPEZ', 'ECOPEZ'), ('FERRY', 'FERRY')], max_length=50)),
                ('conductor', models.CharField(max_length=100)),
                ('placa', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='anticipo',
            name='reteica',
            field=models.CharField(choices=[('0', 'Sin ReteICA'), ('0.003', '0.3%'), ('0.004', '0.4%'), ('0.005', '0.5%'), ('0.006', '0.6%'), ('0.007', '0.7%'), ('0.010', '0.10%')], default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='anticipo',
            name='saldo_a_favor',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
        migrations.AddField(
            model_name='anticipo',
            name='valor_reteica',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='anticipo',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='anticipo',
            name='iva',
            field=models.DecimalField(blank=True, choices=[(0, 'Sin IVA'), (5, '5%'), (19, '19%')], decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='anticipo',
            name='retencion',
            field=models.DecimalField(blank=True, choices=[(0, 'Sin Retención'), (0.625, '0.625%'), (0.1, '0.1%'), (2, '2%'), (2.5, '2.5%'), (3.5, '3.5%'), (4, '4%'), (6, '6%'), (10, '10%'), (11, '11%')], decimal_places=2, max_digits=5, null=True),
        ),
    ]
