# Generated by Django 4.2.9 on 2024-12-09 15:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_reportecombustible_anticipo_reteica_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='archivos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'bmp', 'webp', 'tiff', 'svg', 'pdf', 'xls', 'xlsx'])]),
        ),
    ]
