# Generated by Django 5.0.6 on 2024-08-14 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0007_alter_anticipo_iva_alter_anticipo_retencion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='comentarios',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=10),
        ),
    ]
