# Generated by Django 5.0.6 on 2024-08-14 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0008_solicitud_comentarios_solicitud_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=10),
        ),
        migrations.AlterField(
            model_name='orden',
            name='tiempo_entrega',
            field=models.DateTimeField(),
        ),
    ]
